/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dimension extends org.jooq.impl.TableImpl<genericdwh.db.model.tables.records.DimensionRecord> {

	private static final long serialVersionUID = 34250074;

	/**
	 * The singleton instance of <code>genericdwh.dimension</code>
	 */
	public static final genericdwh.db.model.tables.Dimension DIMENSION = new genericdwh.db.model.tables.Dimension();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<genericdwh.db.model.tables.records.DimensionRecord> getRecordType() {
		return genericdwh.db.model.tables.records.DimensionRecord.class;
	}

	/**
	 * The column <code>genericdwh.dimension.id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.DimensionRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>genericdwh.dimension.name</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.DimensionRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>genericdwh.dimension.category_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.DimensionRecord, java.lang.Long> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>genericdwh.dimension</code> table reference
	 */
	public Dimension() {
		this("dimension", null);
	}

	/**
	 * Create an aliased <code>genericdwh.dimension</code> table reference
	 */
	public Dimension(java.lang.String alias) {
		this(alias, genericdwh.db.model.tables.Dimension.DIMENSION);
	}

	private Dimension(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.DimensionRecord> aliased) {
		this(alias, aliased, null);
	}

	private Dimension(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.DimensionRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, genericdwh.db.model.Genericdwh.GENERICDWH, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<genericdwh.db.model.tables.records.DimensionRecord, java.lang.Long> getIdentity() {
		return genericdwh.db.model.Keys.IDENTITY_DIMENSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionRecord> getPrimaryKey() {
		return genericdwh.db.model.Keys.KEY_DIMENSION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionRecord>>asList(genericdwh.db.model.Keys.KEY_DIMENSION_PRIMARY, genericdwh.db.model.Keys.KEY_DIMENSION_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionRecord, ?>>asList(genericdwh.db.model.Keys.DIMENSION_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public genericdwh.db.model.tables.Dimension as(java.lang.String alias) {
		return new genericdwh.db.model.tables.Dimension(alias, this);
	}

	/**
	 * Rename this table
	 */
	public genericdwh.db.model.tables.Dimension rename(java.lang.String name) {
		return new genericdwh.db.model.tables.Dimension(name, null);
	}
}
