/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dimensions extends org.jooq.impl.TableImpl<genericdwh.db.model.tables.records.DimensionsRecord> {

	private static final long serialVersionUID = -1586096869;

	/**
	 * The singleton instance of <code>dimensions</code>
	 */
	public static final genericdwh.db.model.tables.Dimensions DIMENSIONS = new genericdwh.db.model.tables.Dimensions();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<genericdwh.db.model.tables.records.DimensionsRecord> getRecordType() {
		return genericdwh.db.model.tables.records.DimensionsRecord.class;
	}

	/**
	 * The column <code>dimensions.dimension_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.DimensionsRecord, java.lang.Long> DIMENSION_ID = createField("dimension_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>dimensions.name</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.DimensionsRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>dimensions.category_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.DimensionsRecord, java.lang.Long> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>dimensions</code> table reference
	 */
	public Dimensions() {
		this("dimensions", null);
	}

	/**
	 * Create an aliased <code>dimensions</code> table reference
	 */
	public Dimensions(java.lang.String alias) {
		this(alias, genericdwh.db.model.tables.Dimensions.DIMENSIONS);
	}

	private Dimensions(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.DimensionsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Dimensions(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.DimensionsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, genericdwh.db.model.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<genericdwh.db.model.tables.records.DimensionsRecord, java.lang.Long> getIdentity() {
		return genericdwh.db.model.Keys.IDENTITY_DIMENSIONS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionsRecord> getPrimaryKey() {
		return genericdwh.db.model.Keys.KEY_DIMENSIONS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionsRecord>>asList(genericdwh.db.model.Keys.KEY_DIMENSIONS_PRIMARY, genericdwh.db.model.Keys.KEY_DIMENSIONS_DIMENSION_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionsRecord, ?>>asList(genericdwh.db.model.Keys.DIMENSIONS_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public genericdwh.db.model.tables.Dimensions as(java.lang.String alias) {
		return new genericdwh.db.model.tables.Dimensions(alias, this);
	}

	/**
	 * Rename this table
	 */
	public genericdwh.db.model.tables.Dimensions rename(java.lang.String name) {
		return new genericdwh.db.model.tables.Dimensions(name, null);
	}
}
