/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DimensionHierarchies extends org.jooq.impl.TableImpl<genericdwh.db.model.tables.records.DimensionHierarchiesRecord> {

	private static final long serialVersionUID = -1042824387;

	/**
	 * The singleton instance of <code>dimension_hierarchies</code>
	 */
	public static final genericdwh.db.model.tables.DimensionHierarchies DIMENSION_HIERARCHIES = new genericdwh.db.model.tables.DimensionHierarchies();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<genericdwh.db.model.tables.records.DimensionHierarchiesRecord> getRecordType() {
		return genericdwh.db.model.tables.records.DimensionHierarchiesRecord.class;
	}

	/**
	 * The column <code>dimension_hierarchies.parent_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.DimensionHierarchiesRecord, java.lang.Long> PARENT_ID = createField("parent_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>dimension_hierarchies.child_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.DimensionHierarchiesRecord, java.lang.Long> CHILD_ID = createField("child_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>dimension_hierarchies</code> table reference
	 */
	public DimensionHierarchies() {
		this("dimension_hierarchies", null);
	}

	/**
	 * Create an aliased <code>dimension_hierarchies</code> table reference
	 */
	public DimensionHierarchies(java.lang.String alias) {
		this(alias, genericdwh.db.model.tables.DimensionHierarchies.DIMENSION_HIERARCHIES);
	}

	private DimensionHierarchies(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.DimensionHierarchiesRecord> aliased) {
		this(alias, aliased, null);
	}

	private DimensionHierarchies(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.DimensionHierarchiesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, genericdwh.db.model.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionHierarchiesRecord> getPrimaryKey() {
		return genericdwh.db.model.Keys.KEY_DIMENSION_HIERARCHIES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionHierarchiesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionHierarchiesRecord>>asList(genericdwh.db.model.Keys.KEY_DIMENSION_HIERARCHIES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionHierarchiesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionHierarchiesRecord, ?>>asList(genericdwh.db.model.Keys.DIMENSION_HIERARCHIES_IBFK_1, genericdwh.db.model.Keys.DIMENSION_HIERARCHIES_IBFK_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public genericdwh.db.model.tables.DimensionHierarchies as(java.lang.String alias) {
		return new genericdwh.db.model.tables.DimensionHierarchies(alias, this);
	}

	/**
	 * Rename this table
	 */
	public genericdwh.db.model.tables.DimensionHierarchies rename(java.lang.String name) {
		return new genericdwh.db.model.tables.DimensionHierarchies(name, null);
	}
}
