/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DimensionCombination extends org.jooq.impl.TableImpl<genericdwh.db.model.tables.records.DimensionCombinationRecord> {

	private static final long serialVersionUID = 1845057259;

	/**
	 * The singleton instance of <code>dimension_combination</code>
	 */
	public static final genericdwh.db.model.tables.DimensionCombination DIMENSION_COMBINATION = new genericdwh.db.model.tables.DimensionCombination();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<genericdwh.db.model.tables.records.DimensionCombinationRecord> getRecordType() {
		return genericdwh.db.model.tables.records.DimensionCombinationRecord.class;
	}

	/**
	 * The column <code>dimension_combination.aggregate_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.DimensionCombinationRecord, java.lang.Long> AGGREGATE_ID = createField("aggregate_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>dimension_combination.component_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.DimensionCombinationRecord, java.lang.Long> COMPONENT_ID = createField("component_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>dimension_combination</code> table reference
	 */
	public DimensionCombination() {
		this("dimension_combination", null);
	}

	/**
	 * Create an aliased <code>dimension_combination</code> table reference
	 */
	public DimensionCombination(java.lang.String alias) {
		this(alias, genericdwh.db.model.tables.DimensionCombination.DIMENSION_COMBINATION);
	}

	private DimensionCombination(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.DimensionCombinationRecord> aliased) {
		this(alias, aliased, null);
	}

	private DimensionCombination(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.DimensionCombinationRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, genericdwh.db.model.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionCombinationRecord> getPrimaryKey() {
		return genericdwh.db.model.Keys.KEY_DIMENSION_COMBINATION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionCombinationRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionCombinationRecord>>asList(genericdwh.db.model.Keys.KEY_DIMENSION_COMBINATION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionCombinationRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionCombinationRecord, ?>>asList(genericdwh.db.model.Keys.DIMENSION_COMBINATION_IBFK_1, genericdwh.db.model.Keys.DIMENSION_COMBINATION_IBFK_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public genericdwh.db.model.tables.DimensionCombination as(java.lang.String alias) {
		return new genericdwh.db.model.tables.DimensionCombination(alias, this);
	}

	/**
	 * Rename this table
	 */
	public genericdwh.db.model.tables.DimensionCombination rename(java.lang.String name) {
		return new genericdwh.db.model.tables.DimensionCombination(name, null);
	}
}
