/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DimensionCategories extends org.jooq.impl.TableImpl<genericdwh.db.model.tables.records.DimensionCategoriesRecord> {

	private static final long serialVersionUID = -2114491328;

	/**
	 * The singleton instance of <code>dimension_categories</code>
	 */
	public static final genericdwh.db.model.tables.DimensionCategories DIMENSION_CATEGORIES = new genericdwh.db.model.tables.DimensionCategories();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<genericdwh.db.model.tables.records.DimensionCategoriesRecord> getRecordType() {
		return genericdwh.db.model.tables.records.DimensionCategoriesRecord.class;
	}

	/**
	 * The column <code>dimension_categories.category_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.DimensionCategoriesRecord, java.lang.Long> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>dimension_categories.name</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.DimensionCategoriesRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>dimension_categories</code> table reference
	 */
	public DimensionCategories() {
		this("dimension_categories", null);
	}

	/**
	 * Create an aliased <code>dimension_categories</code> table reference
	 */
	public DimensionCategories(java.lang.String alias) {
		this(alias, genericdwh.db.model.tables.DimensionCategories.DIMENSION_CATEGORIES);
	}

	private DimensionCategories(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.DimensionCategoriesRecord> aliased) {
		this(alias, aliased, null);
	}

	private DimensionCategories(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.DimensionCategoriesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, genericdwh.db.model.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<genericdwh.db.model.tables.records.DimensionCategoriesRecord, java.lang.Long> getIdentity() {
		return genericdwh.db.model.Keys.IDENTITY_DIMENSION_CATEGORIES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionCategoriesRecord> getPrimaryKey() {
		return genericdwh.db.model.Keys.KEY_DIMENSION_CATEGORIES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionCategoriesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionCategoriesRecord>>asList(genericdwh.db.model.Keys.KEY_DIMENSION_CATEGORIES_PRIMARY, genericdwh.db.model.Keys.KEY_DIMENSION_CATEGORIES_CATEGORY_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public genericdwh.db.model.tables.DimensionCategories as(java.lang.String alias) {
		return new genericdwh.db.model.tables.DimensionCategories(alias, this);
	}

	/**
	 * Rename this table
	 */
	public genericdwh.db.model.tables.DimensionCategories rename(java.lang.String name) {
		return new genericdwh.db.model.tables.DimensionCategories(name, null);
	}
}
