/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DimensionCombinations extends org.jooq.impl.TableImpl<genericdwh.db.model.tables.records.DimensionCombinationsRecord> {

	private static final long serialVersionUID = -1521423145;

	/**
	 * The singleton instance of <code>dimension_combinations</code>
	 */
	public static final genericdwh.db.model.tables.DimensionCombinations DIMENSION_COMBINATIONS = new genericdwh.db.model.tables.DimensionCombinations();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<genericdwh.db.model.tables.records.DimensionCombinationsRecord> getRecordType() {
		return genericdwh.db.model.tables.records.DimensionCombinationsRecord.class;
	}

	/**
	 * The column <code>dimension_combinations.aggregate_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.DimensionCombinationsRecord, java.lang.Long> AGGREGATE_ID = createField("aggregate_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>dimension_combinations.component_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.DimensionCombinationsRecord, java.lang.Long> COMPONENT_ID = createField("component_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>dimension_combinations</code> table reference
	 */
	public DimensionCombinations() {
		this("dimension_combinations", null);
	}

	/**
	 * Create an aliased <code>dimension_combinations</code> table reference
	 */
	public DimensionCombinations(java.lang.String alias) {
		this(alias, genericdwh.db.model.tables.DimensionCombinations.DIMENSION_COMBINATIONS);
	}

	private DimensionCombinations(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.DimensionCombinationsRecord> aliased) {
		this(alias, aliased, null);
	}

	private DimensionCombinations(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.DimensionCombinationsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, genericdwh.db.model.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionCombinationsRecord> getPrimaryKey() {
		return genericdwh.db.model.Keys.KEY_DIMENSION_COMBINATIONS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionCombinationsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionCombinationsRecord>>asList(genericdwh.db.model.Keys.KEY_DIMENSION_COMBINATIONS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionCombinationsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionCombinationsRecord, ?>>asList(genericdwh.db.model.Keys.DIMENSION_COMBINATIONS_IBFK_1, genericdwh.db.model.Keys.DIMENSION_COMBINATIONS_IBFK_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public genericdwh.db.model.tables.DimensionCombinations as(java.lang.String alias) {
		return new genericdwh.db.model.tables.DimensionCombinations(alias, this);
	}

	/**
	 * Rename this table
	 */
	public genericdwh.db.model.tables.DimensionCombinations rename(java.lang.String name) {
		return new genericdwh.db.model.tables.DimensionCombinations(name, null);
	}
}
