/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DimensionCategory extends org.jooq.impl.TableImpl<genericdwh.db.model.tables.records.DimensionCategoryRecord> {

	private static final long serialVersionUID = 835873649;

	/**
	 * The singleton instance of <code>genericdwh.dimension_category</code>
	 */
	public static final genericdwh.db.model.tables.DimensionCategory DIMENSION_CATEGORY = new genericdwh.db.model.tables.DimensionCategory();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<genericdwh.db.model.tables.records.DimensionCategoryRecord> getRecordType() {
		return genericdwh.db.model.tables.records.DimensionCategoryRecord.class;
	}

	/**
	 * The column <code>genericdwh.dimension_category.id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.DimensionCategoryRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>genericdwh.dimension_category.name</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.DimensionCategoryRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>genericdwh.dimension_category</code> table reference
	 */
	public DimensionCategory() {
		this("dimension_category", null);
	}

	/**
	 * Create an aliased <code>genericdwh.dimension_category</code> table reference
	 */
	public DimensionCategory(java.lang.String alias) {
		this(alias, genericdwh.db.model.tables.DimensionCategory.DIMENSION_CATEGORY);
	}

	private DimensionCategory(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.DimensionCategoryRecord> aliased) {
		this(alias, aliased, null);
	}

	private DimensionCategory(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.DimensionCategoryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, genericdwh.db.model.Genericdwh.GENERICDWH, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<genericdwh.db.model.tables.records.DimensionCategoryRecord, java.lang.Long> getIdentity() {
		return genericdwh.db.model.Keys.IDENTITY_DIMENSION_CATEGORY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionCategoryRecord> getPrimaryKey() {
		return genericdwh.db.model.Keys.KEY_DIMENSION_CATEGORY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionCategoryRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionCategoryRecord>>asList(genericdwh.db.model.Keys.KEY_DIMENSION_CATEGORY_PRIMARY, genericdwh.db.model.Keys.KEY_DIMENSION_CATEGORY_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public genericdwh.db.model.tables.DimensionCategory as(java.lang.String alias) {
		return new genericdwh.db.model.tables.DimensionCategory(alias, this);
	}

	/**
	 * Rename this table
	 */
	public genericdwh.db.model.tables.DimensionCategory rename(java.lang.String name) {
		return new genericdwh.db.model.tables.DimensionCategory(name, null);
	}
}
