/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FactUnits extends org.jooq.impl.TableImpl<genericdwh.db.model.tables.records.FactUnitsRecord> {

	private static final long serialVersionUID = 1918132341;

	/**
	 * The singleton instance of <code>fact_units</code>
	 */
	public static final genericdwh.db.model.tables.FactUnits FACT_UNITS = new genericdwh.db.model.tables.FactUnits();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<genericdwh.db.model.tables.records.FactUnitsRecord> getRecordType() {
		return genericdwh.db.model.tables.records.FactUnitsRecord.class;
	}

	/**
	 * The column <code>fact_units.unit_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.FactUnitsRecord, java.lang.Long> UNIT_ID = createField("unit_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>fact_units.unit_name</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.FactUnitsRecord, java.lang.String> UNIT_NAME = createField("unit_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>fact_units.unit_symbol</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.FactUnitsRecord, java.lang.String> UNIT_SYMBOL = createField("unit_symbol", org.jooq.impl.SQLDataType.VARCHAR.length(25).nullable(false), this, "");

	/**
	 * Create a <code>fact_units</code> table reference
	 */
	public FactUnits() {
		this("fact_units", null);
	}

	/**
	 * Create an aliased <code>fact_units</code> table reference
	 */
	public FactUnits(java.lang.String alias) {
		this(alias, genericdwh.db.model.tables.FactUnits.FACT_UNITS);
	}

	private FactUnits(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.FactUnitsRecord> aliased) {
		this(alias, aliased, null);
	}

	private FactUnits(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.FactUnitsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, genericdwh.db.model.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<genericdwh.db.model.tables.records.FactUnitsRecord> getPrimaryKey() {
		return genericdwh.db.model.Keys.KEY_FACT_UNITS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<genericdwh.db.model.tables.records.FactUnitsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<genericdwh.db.model.tables.records.FactUnitsRecord>>asList(genericdwh.db.model.Keys.KEY_FACT_UNITS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public genericdwh.db.model.tables.FactUnits as(java.lang.String alias) {
		return new genericdwh.db.model.tables.FactUnits(alias, this);
	}

	/**
	 * Rename this table
	 */
	public genericdwh.db.model.tables.FactUnits rename(java.lang.String name) {
		return new genericdwh.db.model.tables.FactUnits(name, null);
	}
}
