/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Facts extends org.jooq.impl.TableImpl<genericdwh.db.model.tables.records.FactsRecord> {

	private static final long serialVersionUID = -1869791765;

	/**
	 * The singleton instance of <code>facts</code>
	 */
	public static final genericdwh.db.model.tables.Facts FACTS = new genericdwh.db.model.tables.Facts();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<genericdwh.db.model.tables.records.FactsRecord> getRecordType() {
		return genericdwh.db.model.tables.records.FactsRecord.class;
	}

	/**
	 * The column <code>facts.ratio_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.FactsRecord, java.lang.Long> RATIO_ID = createField("ratio_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>facts.reference_object_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.FactsRecord, java.lang.Long> REFERENCE_OBJECT_ID = createField("reference_object_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>facts.value</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.FactsRecord, java.lang.Double> VALUE = createField("value", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

	/**
	 * The column <code>facts.unit_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.FactsRecord, java.lang.Long> UNIT_ID = createField("unit_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>facts</code> table reference
	 */
	public Facts() {
		this("facts", null);
	}

	/**
	 * Create an aliased <code>facts</code> table reference
	 */
	public Facts(java.lang.String alias) {
		this(alias, genericdwh.db.model.tables.Facts.FACTS);
	}

	private Facts(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.FactsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Facts(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.FactsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, genericdwh.db.model.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<genericdwh.db.model.tables.records.FactsRecord> getPrimaryKey() {
		return genericdwh.db.model.Keys.KEY_FACTS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<genericdwh.db.model.tables.records.FactsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<genericdwh.db.model.tables.records.FactsRecord>>asList(genericdwh.db.model.Keys.KEY_FACTS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<genericdwh.db.model.tables.records.FactsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<genericdwh.db.model.tables.records.FactsRecord, ?>>asList(genericdwh.db.model.Keys.FACTS_IBFK_1, genericdwh.db.model.Keys.FACTS_IBFK_2, genericdwh.db.model.Keys.UNIT_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public genericdwh.db.model.tables.Facts as(java.lang.String alias) {
		return new genericdwh.db.model.tables.Facts(alias, this);
	}

	/**
	 * Rename this table
	 */
	public genericdwh.db.model.tables.Facts rename(java.lang.String name) {
		return new genericdwh.db.model.tables.Facts(name, null);
	}
}
