/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ratio extends org.jooq.impl.TableImpl<genericdwh.db.model.tables.records.RatioRecord> {

	private static final long serialVersionUID = -1061994955;

	/**
	 * The singleton instance of <code>ratio</code>
	 */
	public static final genericdwh.db.model.tables.Ratio RATIO = new genericdwh.db.model.tables.Ratio();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<genericdwh.db.model.tables.records.RatioRecord> getRecordType() {
		return genericdwh.db.model.tables.records.RatioRecord.class;
	}

	/**
	 * The column <code>ratio.id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.RatioRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>ratio.name</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.RatioRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>ratio.category_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.RatioRecord, java.lang.Long> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>ratio</code> table reference
	 */
	public Ratio() {
		this("ratio", null);
	}

	/**
	 * Create an aliased <code>ratio</code> table reference
	 */
	public Ratio(java.lang.String alias) {
		this(alias, genericdwh.db.model.tables.Ratio.RATIO);
	}

	private Ratio(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.RatioRecord> aliased) {
		this(alias, aliased, null);
	}

	private Ratio(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.RatioRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, genericdwh.db.model.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<genericdwh.db.model.tables.records.RatioRecord, java.lang.Long> getIdentity() {
		return genericdwh.db.model.Keys.IDENTITY_RATIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<genericdwh.db.model.tables.records.RatioRecord> getPrimaryKey() {
		return genericdwh.db.model.Keys.KEY_RATIO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<genericdwh.db.model.tables.records.RatioRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<genericdwh.db.model.tables.records.RatioRecord>>asList(genericdwh.db.model.Keys.KEY_RATIO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<genericdwh.db.model.tables.records.RatioRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<genericdwh.db.model.tables.records.RatioRecord, ?>>asList(genericdwh.db.model.Keys.RATIO_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public genericdwh.db.model.tables.Ratio as(java.lang.String alias) {
		return new genericdwh.db.model.tables.Ratio(alias, this);
	}

	/**
	 * Rename this table
	 */
	public genericdwh.db.model.tables.Ratio rename(java.lang.String name) {
		return new genericdwh.db.model.tables.Ratio(name, null);
	}
}
