/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RatioCategory extends org.jooq.impl.TableImpl<genericdwh.db.model.tables.records.RatioCategoryRecord> {

	private static final long serialVersionUID = -1420097249;

	/**
	 * The singleton instance of <code>ratio_category</code>
	 */
	public static final genericdwh.db.model.tables.RatioCategory RATIO_CATEGORY = new genericdwh.db.model.tables.RatioCategory();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<genericdwh.db.model.tables.records.RatioCategoryRecord> getRecordType() {
		return genericdwh.db.model.tables.records.RatioCategoryRecord.class;
	}

	/**
	 * The column <code>ratio_category.id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.RatioCategoryRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>ratio_category.name</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.RatioCategoryRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>ratio_category</code> table reference
	 */
	public RatioCategory() {
		this("ratio_category", null);
	}

	/**
	 * Create an aliased <code>ratio_category</code> table reference
	 */
	public RatioCategory(java.lang.String alias) {
		this(alias, genericdwh.db.model.tables.RatioCategory.RATIO_CATEGORY);
	}

	private RatioCategory(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.RatioCategoryRecord> aliased) {
		this(alias, aliased, null);
	}

	private RatioCategory(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.RatioCategoryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, genericdwh.db.model.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<genericdwh.db.model.tables.records.RatioCategoryRecord, java.lang.Long> getIdentity() {
		return genericdwh.db.model.Keys.IDENTITY_RATIO_CATEGORY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<genericdwh.db.model.tables.records.RatioCategoryRecord> getPrimaryKey() {
		return genericdwh.db.model.Keys.KEY_RATIO_CATEGORY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<genericdwh.db.model.tables.records.RatioCategoryRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<genericdwh.db.model.tables.records.RatioCategoryRecord>>asList(genericdwh.db.model.Keys.KEY_RATIO_CATEGORY_PRIMARY, genericdwh.db.model.Keys.KEY_RATIO_CATEGORY_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public genericdwh.db.model.tables.RatioCategory as(java.lang.String alias) {
		return new genericdwh.db.model.tables.RatioCategory(alias, this);
	}

	/**
	 * Rename this table
	 */
	public genericdwh.db.model.tables.RatioCategory rename(java.lang.String name) {
		return new genericdwh.db.model.tables.RatioCategory(name, null);
	}
}
