/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ratios extends org.jooq.impl.TableImpl<genericdwh.db.model.tables.records.RatiosRecord> {

	private static final long serialVersionUID = -164131714;

	/**
	 * The singleton instance of <code>ratios</code>
	 */
	public static final genericdwh.db.model.tables.Ratios RATIOS = new genericdwh.db.model.tables.Ratios();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<genericdwh.db.model.tables.records.RatiosRecord> getRecordType() {
		return genericdwh.db.model.tables.records.RatiosRecord.class;
	}

	/**
	 * The column <code>ratios.ratio_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.RatiosRecord, java.lang.Long> RATIO_ID = createField("ratio_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>ratios.name</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.RatiosRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>ratios.category_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.RatiosRecord, java.lang.Long> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>ratios</code> table reference
	 */
	public Ratios() {
		this("ratios", null);
	}

	/**
	 * Create an aliased <code>ratios</code> table reference
	 */
	public Ratios(java.lang.String alias) {
		this(alias, genericdwh.db.model.tables.Ratios.RATIOS);
	}

	private Ratios(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.RatiosRecord> aliased) {
		this(alias, aliased, null);
	}

	private Ratios(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.RatiosRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, genericdwh.db.model.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<genericdwh.db.model.tables.records.RatiosRecord, java.lang.Long> getIdentity() {
		return genericdwh.db.model.Keys.IDENTITY_RATIOS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<genericdwh.db.model.tables.records.RatiosRecord> getPrimaryKey() {
		return genericdwh.db.model.Keys.KEY_RATIOS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<genericdwh.db.model.tables.records.RatiosRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<genericdwh.db.model.tables.records.RatiosRecord>>asList(genericdwh.db.model.Keys.KEY_RATIOS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<genericdwh.db.model.tables.records.RatiosRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<genericdwh.db.model.tables.records.RatiosRecord, ?>>asList(genericdwh.db.model.Keys.RATIOS_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public genericdwh.db.model.tables.Ratios as(java.lang.String alias) {
		return new genericdwh.db.model.tables.Ratios(alias, this);
	}

	/**
	 * Rename this table
	 */
	public genericdwh.db.model.tables.Ratios rename(java.lang.String name) {
		return new genericdwh.db.model.tables.Ratios(name, null);
	}
}
