/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RatioCategories extends org.jooq.impl.TableImpl<genericdwh.db.model.tables.records.RatioCategoriesRecord> {

	private static final long serialVersionUID = 148570567;

	/**
	 * The singleton instance of <code>ratio_categories</code>
	 */
	public static final genericdwh.db.model.tables.RatioCategories RATIO_CATEGORIES = new genericdwh.db.model.tables.RatioCategories();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<genericdwh.db.model.tables.records.RatioCategoriesRecord> getRecordType() {
		return genericdwh.db.model.tables.records.RatioCategoriesRecord.class;
	}

	/**
	 * The column <code>ratio_categories.category_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.RatioCategoriesRecord, java.lang.Long> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>ratio_categories.name</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.RatioCategoriesRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>ratio_categories</code> table reference
	 */
	public RatioCategories() {
		this("ratio_categories", null);
	}

	/**
	 * Create an aliased <code>ratio_categories</code> table reference
	 */
	public RatioCategories(java.lang.String alias) {
		this(alias, genericdwh.db.model.tables.RatioCategories.RATIO_CATEGORIES);
	}

	private RatioCategories(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.RatioCategoriesRecord> aliased) {
		this(alias, aliased, null);
	}

	private RatioCategories(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.RatioCategoriesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, genericdwh.db.model.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<genericdwh.db.model.tables.records.RatioCategoriesRecord, java.lang.Long> getIdentity() {
		return genericdwh.db.model.Keys.IDENTITY_RATIO_CATEGORIES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<genericdwh.db.model.tables.records.RatioCategoriesRecord> getPrimaryKey() {
		return genericdwh.db.model.Keys.KEY_RATIO_CATEGORIES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<genericdwh.db.model.tables.records.RatioCategoriesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<genericdwh.db.model.tables.records.RatioCategoriesRecord>>asList(genericdwh.db.model.Keys.KEY_RATIO_CATEGORIES_PRIMARY, genericdwh.db.model.Keys.KEY_RATIO_CATEGORIES_CATEGORY_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public genericdwh.db.model.tables.RatioCategories as(java.lang.String alias) {
		return new genericdwh.db.model.tables.RatioCategories(alias, this);
	}

	/**
	 * Rename this table
	 */
	public genericdwh.db.model.tables.RatioCategories rename(java.lang.String name) {
		return new genericdwh.db.model.tables.RatioCategories(name, null);
	}
}
