/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RatioRelations extends org.jooq.impl.TableImpl<genericdwh.db.model.tables.records.RatioRelationsRecord> {

	private static final long serialVersionUID = 121028531;

	/**
	 * The singleton instance of <code>ratio_relations</code>
	 */
	public static final genericdwh.db.model.tables.RatioRelations RATIO_RELATIONS = new genericdwh.db.model.tables.RatioRelations();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<genericdwh.db.model.tables.records.RatioRelationsRecord> getRecordType() {
		return genericdwh.db.model.tables.records.RatioRelationsRecord.class;
	}

	/**
	 * The column <code>ratio_relations.dependent_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.RatioRelationsRecord, java.lang.Long> DEPENDENT_ID = createField("dependent_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>ratio_relations.dependency_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.RatioRelationsRecord, java.lang.Long> DEPENDENCY_ID = createField("dependency_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>ratio_relations</code> table reference
	 */
	public RatioRelations() {
		this("ratio_relations", null);
	}

	/**
	 * Create an aliased <code>ratio_relations</code> table reference
	 */
	public RatioRelations(java.lang.String alias) {
		this(alias, genericdwh.db.model.tables.RatioRelations.RATIO_RELATIONS);
	}

	private RatioRelations(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.RatioRelationsRecord> aliased) {
		this(alias, aliased, null);
	}

	private RatioRelations(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.RatioRelationsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, genericdwh.db.model.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<genericdwh.db.model.tables.records.RatioRelationsRecord> getPrimaryKey() {
		return genericdwh.db.model.Keys.KEY_RATIO_RELATIONS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<genericdwh.db.model.tables.records.RatioRelationsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<genericdwh.db.model.tables.records.RatioRelationsRecord>>asList(genericdwh.db.model.Keys.KEY_RATIO_RELATIONS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<genericdwh.db.model.tables.records.RatioRelationsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<genericdwh.db.model.tables.records.RatioRelationsRecord, ?>>asList(genericdwh.db.model.Keys.RATIO_RELATIONS_IBFK_1, genericdwh.db.model.Keys.RATIO_RELATIONS_IBFK_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public genericdwh.db.model.tables.RatioRelations as(java.lang.String alias) {
		return new genericdwh.db.model.tables.RatioRelations(alias, this);
	}

	/**
	 * Rename this table
	 */
	public genericdwh.db.model.tables.RatioRelations rename(java.lang.String name) {
		return new genericdwh.db.model.tables.RatioRelations(name, null);
	}
}
