/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReferenceObjects extends org.jooq.impl.TableImpl<genericdwh.db.model.tables.records.ReferenceObjectsRecord> {

	private static final long serialVersionUID = 1934520132;

	/**
	 * The singleton instance of <code>reference_objects</code>
	 */
	public static final genericdwh.db.model.tables.ReferenceObjects REFERENCE_OBJECTS = new genericdwh.db.model.tables.ReferenceObjects();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<genericdwh.db.model.tables.records.ReferenceObjectsRecord> getRecordType() {
		return genericdwh.db.model.tables.records.ReferenceObjectsRecord.class;
	}

	/**
	 * The column <code>reference_objects.reference_object_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.ReferenceObjectsRecord, java.lang.Long> REFERENCE_OBJECT_ID = createField("reference_object_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>reference_objects.dimension_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.ReferenceObjectsRecord, java.lang.Long> DIMENSION_ID = createField("dimension_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>reference_objects.name</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.ReferenceObjectsRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>reference_objects</code> table reference
	 */
	public ReferenceObjects() {
		this("reference_objects", null);
	}

	/**
	 * Create an aliased <code>reference_objects</code> table reference
	 */
	public ReferenceObjects(java.lang.String alias) {
		this(alias, genericdwh.db.model.tables.ReferenceObjects.REFERENCE_OBJECTS);
	}

	private ReferenceObjects(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.ReferenceObjectsRecord> aliased) {
		this(alias, aliased, null);
	}

	private ReferenceObjects(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.ReferenceObjectsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, genericdwh.db.model.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<genericdwh.db.model.tables.records.ReferenceObjectsRecord, java.lang.Long> getIdentity() {
		return genericdwh.db.model.Keys.IDENTITY_REFERENCE_OBJECTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectsRecord> getPrimaryKey() {
		return genericdwh.db.model.Keys.KEY_REFERENCE_OBJECTS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectsRecord>>asList(genericdwh.db.model.Keys.KEY_REFERENCE_OBJECTS_PRIMARY, genericdwh.db.model.Keys.KEY_REFERENCE_OBJECTS_REFERENCE_OBJECT_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectsRecord, ?>>asList(genericdwh.db.model.Keys.REFERENCE_OBJECTS_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public genericdwh.db.model.tables.ReferenceObjects as(java.lang.String alias) {
		return new genericdwh.db.model.tables.ReferenceObjects(alias, this);
	}

	/**
	 * Rename this table
	 */
	public genericdwh.db.model.tables.ReferenceObjects rename(java.lang.String name) {
		return new genericdwh.db.model.tables.ReferenceObjects(name, null);
	}
}
