/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReferenceObjectCombination extends org.jooq.impl.TableImpl<genericdwh.db.model.tables.records.ReferenceObjectCombinationRecord> {

	private static final long serialVersionUID = 1359413306;

	/**
	 * The singleton instance of <code>genericdwh.reference_object_combination</code>
	 */
	public static final genericdwh.db.model.tables.ReferenceObjectCombination REFERENCE_OBJECT_COMBINATION = new genericdwh.db.model.tables.ReferenceObjectCombination();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<genericdwh.db.model.tables.records.ReferenceObjectCombinationRecord> getRecordType() {
		return genericdwh.db.model.tables.records.ReferenceObjectCombinationRecord.class;
	}

	/**
	 * The column <code>genericdwh.reference_object_combination.aggregate_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.ReferenceObjectCombinationRecord, java.lang.Long> AGGREGATE_ID = createField("aggregate_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>genericdwh.reference_object_combination.component_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.ReferenceObjectCombinationRecord, java.lang.Long> COMPONENT_ID = createField("component_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>genericdwh.reference_object_combination</code> table reference
	 */
	public ReferenceObjectCombination() {
		this("reference_object_combination", null);
	}

	/**
	 * Create an aliased <code>genericdwh.reference_object_combination</code> table reference
	 */
	public ReferenceObjectCombination(java.lang.String alias) {
		this(alias, genericdwh.db.model.tables.ReferenceObjectCombination.REFERENCE_OBJECT_COMBINATION);
	}

	private ReferenceObjectCombination(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.ReferenceObjectCombinationRecord> aliased) {
		this(alias, aliased, null);
	}

	private ReferenceObjectCombination(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.ReferenceObjectCombinationRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, genericdwh.db.model.Genericdwh.GENERICDWH, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectCombinationRecord> getPrimaryKey() {
		return genericdwh.db.model.Keys.KEY_REFERENCE_OBJECT_COMBINATION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectCombinationRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectCombinationRecord>>asList(genericdwh.db.model.Keys.KEY_REFERENCE_OBJECT_COMBINATION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectCombinationRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectCombinationRecord, ?>>asList(genericdwh.db.model.Keys.REFERENCE_OBJECT_COMBINATION_IBFK_1, genericdwh.db.model.Keys.REFERENCE_OBJECT_COMBINATION_IBFK_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public genericdwh.db.model.tables.ReferenceObjectCombination as(java.lang.String alias) {
		return new genericdwh.db.model.tables.ReferenceObjectCombination(alias, this);
	}

	/**
	 * Rename this table
	 */
	public genericdwh.db.model.tables.ReferenceObjectCombination rename(java.lang.String name) {
		return new genericdwh.db.model.tables.ReferenceObjectCombination(name, null);
	}
}
