/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReferenceObjectHierarchies extends org.jooq.impl.TableImpl<genericdwh.db.model.tables.records.ReferenceObjectHierarchiesRecord> {

	private static final long serialVersionUID = 365047391;

	/**
	 * The singleton instance of <code>reference_object_hierarchies</code>
	 */
	public static final genericdwh.db.model.tables.ReferenceObjectHierarchies REFERENCE_OBJECT_HIERARCHIES = new genericdwh.db.model.tables.ReferenceObjectHierarchies();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<genericdwh.db.model.tables.records.ReferenceObjectHierarchiesRecord> getRecordType() {
		return genericdwh.db.model.tables.records.ReferenceObjectHierarchiesRecord.class;
	}

	/**
	 * The column <code>reference_object_hierarchies.parent_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.ReferenceObjectHierarchiesRecord, java.lang.Long> PARENT_ID = createField("parent_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>reference_object_hierarchies.child_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.ReferenceObjectHierarchiesRecord, java.lang.Long> CHILD_ID = createField("child_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>reference_object_hierarchies</code> table reference
	 */
	public ReferenceObjectHierarchies() {
		this("reference_object_hierarchies", null);
	}

	/**
	 * Create an aliased <code>reference_object_hierarchies</code> table reference
	 */
	public ReferenceObjectHierarchies(java.lang.String alias) {
		this(alias, genericdwh.db.model.tables.ReferenceObjectHierarchies.REFERENCE_OBJECT_HIERARCHIES);
	}

	private ReferenceObjectHierarchies(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.ReferenceObjectHierarchiesRecord> aliased) {
		this(alias, aliased, null);
	}

	private ReferenceObjectHierarchies(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.ReferenceObjectHierarchiesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, genericdwh.db.model.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectHierarchiesRecord> getPrimaryKey() {
		return genericdwh.db.model.Keys.KEY_REFERENCE_OBJECT_HIERARCHIES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectHierarchiesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectHierarchiesRecord>>asList(genericdwh.db.model.Keys.KEY_REFERENCE_OBJECT_HIERARCHIES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectHierarchiesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectHierarchiesRecord, ?>>asList(genericdwh.db.model.Keys.REFERENCE_OBJECT_HIERARCHIES_IBFK_1, genericdwh.db.model.Keys.REFERENCE_OBJECT_HIERARCHIES_IBFK_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public genericdwh.db.model.tables.ReferenceObjectHierarchies as(java.lang.String alias) {
		return new genericdwh.db.model.tables.ReferenceObjectHierarchies(alias, this);
	}

	/**
	 * Rename this table
	 */
	public genericdwh.db.model.tables.ReferenceObjectHierarchies rename(java.lang.String name) {
		return new genericdwh.db.model.tables.ReferenceObjectHierarchies(name, null);
	}
}
