/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReferenceObjectHierarchy extends org.jooq.impl.TableImpl<genericdwh.db.model.tables.records.ReferenceObjectHierarchyRecord> {

	private static final long serialVersionUID = 1077051146;

	/**
	 * The singleton instance of <code>genericdwh.reference_object_hierarchy</code>
	 */
	public static final genericdwh.db.model.tables.ReferenceObjectHierarchy REFERENCE_OBJECT_HIERARCHY = new genericdwh.db.model.tables.ReferenceObjectHierarchy();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<genericdwh.db.model.tables.records.ReferenceObjectHierarchyRecord> getRecordType() {
		return genericdwh.db.model.tables.records.ReferenceObjectHierarchyRecord.class;
	}

	/**
	 * The column <code>genericdwh.reference_object_hierarchy.parent_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.ReferenceObjectHierarchyRecord, java.lang.Long> PARENT_ID = createField("parent_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>genericdwh.reference_object_hierarchy.child_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.ReferenceObjectHierarchyRecord, java.lang.Long> CHILD_ID = createField("child_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>genericdwh.reference_object_hierarchy</code> table reference
	 */
	public ReferenceObjectHierarchy() {
		this("reference_object_hierarchy", null);
	}

	/**
	 * Create an aliased <code>genericdwh.reference_object_hierarchy</code> table reference
	 */
	public ReferenceObjectHierarchy(java.lang.String alias) {
		this(alias, genericdwh.db.model.tables.ReferenceObjectHierarchy.REFERENCE_OBJECT_HIERARCHY);
	}

	private ReferenceObjectHierarchy(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.ReferenceObjectHierarchyRecord> aliased) {
		this(alias, aliased, null);
	}

	private ReferenceObjectHierarchy(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.ReferenceObjectHierarchyRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, genericdwh.db.model.Genericdwh.GENERICDWH, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectHierarchyRecord> getPrimaryKey() {
		return genericdwh.db.model.Keys.KEY_REFERENCE_OBJECT_HIERARCHY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectHierarchyRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectHierarchyRecord>>asList(genericdwh.db.model.Keys.KEY_REFERENCE_OBJECT_HIERARCHY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectHierarchyRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectHierarchyRecord, ?>>asList(genericdwh.db.model.Keys.REFERENCE_OBJECT_HIERARCHY_IBFK_1, genericdwh.db.model.Keys.REFERENCE_OBJECT_HIERARCHY_IBFK_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public genericdwh.db.model.tables.ReferenceObjectHierarchy as(java.lang.String alias) {
		return new genericdwh.db.model.tables.ReferenceObjectHierarchy(alias, this);
	}

	/**
	 * Rename this table
	 */
	public genericdwh.db.model.tables.ReferenceObjectHierarchy rename(java.lang.String name) {
		return new genericdwh.db.model.tables.ReferenceObjectHierarchy(name, null);
	}
}
