/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReferenceObject extends org.jooq.impl.TableImpl<genericdwh.db.model.tables.records.ReferenceObjectRecord> {

	private static final long serialVersionUID = -506180485;

	/**
	 * The singleton instance of <code>genericdwh.reference_object</code>
	 */
	public static final genericdwh.db.model.tables.ReferenceObject REFERENCE_OBJECT = new genericdwh.db.model.tables.ReferenceObject();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<genericdwh.db.model.tables.records.ReferenceObjectRecord> getRecordType() {
		return genericdwh.db.model.tables.records.ReferenceObjectRecord.class;
	}

	/**
	 * The column <code>genericdwh.reference_object.id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.ReferenceObjectRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>genericdwh.reference_object.dimension_id</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.ReferenceObjectRecord, java.lang.Long> DIMENSION_ID = createField("dimension_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>genericdwh.reference_object.name</code>.
	 */
	public final org.jooq.TableField<genericdwh.db.model.tables.records.ReferenceObjectRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>genericdwh.reference_object</code> table reference
	 */
	public ReferenceObject() {
		this("reference_object", null);
	}

	/**
	 * Create an aliased <code>genericdwh.reference_object</code> table reference
	 */
	public ReferenceObject(java.lang.String alias) {
		this(alias, genericdwh.db.model.tables.ReferenceObject.REFERENCE_OBJECT);
	}

	private ReferenceObject(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.ReferenceObjectRecord> aliased) {
		this(alias, aliased, null);
	}

	private ReferenceObject(java.lang.String alias, org.jooq.Table<genericdwh.db.model.tables.records.ReferenceObjectRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, genericdwh.db.model.Genericdwh.GENERICDWH, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<genericdwh.db.model.tables.records.ReferenceObjectRecord, java.lang.Long> getIdentity() {
		return genericdwh.db.model.Keys.IDENTITY_REFERENCE_OBJECT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectRecord> getPrimaryKey() {
		return genericdwh.db.model.Keys.KEY_REFERENCE_OBJECT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectRecord>>asList(genericdwh.db.model.Keys.KEY_REFERENCE_OBJECT_PRIMARY, genericdwh.db.model.Keys.KEY_REFERENCE_OBJECT_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectRecord, ?>>asList(genericdwh.db.model.Keys.REFERENCE_OBJECT_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public genericdwh.db.model.tables.ReferenceObject as(java.lang.String alias) {
		return new genericdwh.db.model.tables.ReferenceObject(alias, this);
	}

	/**
	 * Rename this table
	 */
	public genericdwh.db.model.tables.ReferenceObject rename(java.lang.String name) {
		return new genericdwh.db.model.tables.ReferenceObject(name, null);
	}
}
