/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FactUnitsRecord extends org.jooq.impl.UpdatableRecordImpl<genericdwh.db.model.tables.records.FactUnitsRecord> implements org.jooq.Record3<java.lang.Long, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -766889433;

	/**
	 * Setter for <code>fact_units.unit_id</code>.
	 */
	public void setUnitId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>fact_units.unit_id</code>.
	 */
	public java.lang.Long getUnitId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>fact_units.unit_name</code>.
	 */
	public void setUnitName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>fact_units.unit_name</code>.
	 */
	public java.lang.String getUnitName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>fact_units.unit_symbol</code>.
	 */
	public void setUnitSymbol(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>fact_units.unit_symbol</code>.
	 */
	public java.lang.String getUnitSymbol() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return genericdwh.db.model.tables.FactUnits.FACT_UNITS.UNIT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return genericdwh.db.model.tables.FactUnits.FACT_UNITS.UNIT_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return genericdwh.db.model.tables.FactUnits.FACT_UNITS.UNIT_SYMBOL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getUnitId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUnitName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getUnitSymbol();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FactUnitsRecord value1(java.lang.Long value) {
		setUnitId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FactUnitsRecord value2(java.lang.String value) {
		setUnitName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FactUnitsRecord value3(java.lang.String value) {
		setUnitSymbol(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FactUnitsRecord values(java.lang.Long value1, java.lang.String value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FactUnitsRecord
	 */
	public FactUnitsRecord() {
		super(genericdwh.db.model.tables.FactUnits.FACT_UNITS);
	}

	/**
	 * Create a detached, initialised FactUnitsRecord
	 */
	public FactUnitsRecord(java.lang.Long unitId, java.lang.String unitName, java.lang.String unitSymbol) {
		super(genericdwh.db.model.tables.FactUnits.FACT_UNITS);

		setValue(0, unitId);
		setValue(1, unitName);
		setValue(2, unitSymbol);
	}
}
