/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FactsRecord extends org.jooq.impl.UpdatableRecordImpl<genericdwh.db.model.tables.records.FactsRecord> implements org.jooq.Record4<java.lang.Long, java.lang.Long, java.lang.Double, java.lang.Long> {

	private static final long serialVersionUID = 1637534031;

	/**
	 * Setter for <code>facts.ratio_id</code>.
	 */
	public void setRatioId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>facts.ratio_id</code>.
	 */
	public java.lang.Long getRatioId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>facts.reference_object_id</code>.
	 */
	public void setReferenceObjectId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>facts.reference_object_id</code>.
	 */
	public java.lang.Long getReferenceObjectId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>facts.value</code>.
	 */
	public void setValue(java.lang.Double value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>facts.value</code>.
	 */
	public java.lang.Double getValue() {
		return (java.lang.Double) getValue(2);
	}

	/**
	 * Setter for <code>facts.unit_id</code>.
	 */
	public void setUnitId(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>facts.unit_id</code>.
	 */
	public java.lang.Long getUnitId() {
		return (java.lang.Long) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.Long, java.lang.Long> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Long, java.lang.Long, java.lang.Double, java.lang.Long> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Long, java.lang.Long, java.lang.Double, java.lang.Long> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return genericdwh.db.model.tables.Facts.FACTS.RATIO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return genericdwh.db.model.tables.Facts.FACTS.REFERENCE_OBJECT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field3() {
		return genericdwh.db.model.tables.Facts.FACTS.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return genericdwh.db.model.tables.Facts.FACTS.UNIT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getRatioId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getReferenceObjectId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value3() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getUnitId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FactsRecord value1(java.lang.Long value) {
		setRatioId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FactsRecord value2(java.lang.Long value) {
		setReferenceObjectId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FactsRecord value3(java.lang.Double value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FactsRecord value4(java.lang.Long value) {
		setUnitId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FactsRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.Double value3, java.lang.Long value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FactsRecord
	 */
	public FactsRecord() {
		super(genericdwh.db.model.tables.Facts.FACTS);
	}

	/**
	 * Create a detached, initialised FactsRecord
	 */
	public FactsRecord(java.lang.Long ratioId, java.lang.Long referenceObjectId, java.lang.Double value, java.lang.Long unitId) {
		super(genericdwh.db.model.tables.Facts.FACTS);

		setValue(0, ratioId);
		setValue(1, referenceObjectId);
		setValue(2, value);
		setValue(3, unitId);
	}
}
