/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RatiosRecord extends org.jooq.impl.UpdatableRecordImpl<genericdwh.db.model.tables.records.RatiosRecord> implements org.jooq.Record3<java.lang.Long, java.lang.String, java.lang.Long> {

	private static final long serialVersionUID = 926021210;

	/**
	 * Setter for <code>ratios.ratio_id</code>.
	 */
	public void setRatioId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ratios.ratio_id</code>.
	 */
	public java.lang.Long getRatioId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>ratios.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ratios.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>ratios.category_id</code>.
	 */
	public void setCategoryId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ratios.category_id</code>.
	 */
	public java.lang.Long getCategoryId() {
		return (java.lang.Long) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.Long> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.Long> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return genericdwh.db.model.tables.Ratios.RATIOS.RATIO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return genericdwh.db.model.tables.Ratios.RATIOS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return genericdwh.db.model.tables.Ratios.RATIOS.CATEGORY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getRatioId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getCategoryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RatiosRecord value1(java.lang.Long value) {
		setRatioId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RatiosRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RatiosRecord value3(java.lang.Long value) {
		setCategoryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RatiosRecord values(java.lang.Long value1, java.lang.String value2, java.lang.Long value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RatiosRecord
	 */
	public RatiosRecord() {
		super(genericdwh.db.model.tables.Ratios.RATIOS);
	}

	/**
	 * Create a detached, initialised RatiosRecord
	 */
	public RatiosRecord(java.lang.Long ratioId, java.lang.String name, java.lang.Long categoryId) {
		super(genericdwh.db.model.tables.Ratios.RATIOS);

		setValue(0, ratioId);
		setValue(1, name);
		setValue(2, categoryId);
	}
}
