/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RatioRelationsRecord extends org.jooq.impl.UpdatableRecordImpl<genericdwh.db.model.tables.records.RatioRelationsRecord> implements org.jooq.Record2<java.lang.Long, java.lang.Long> {

	private static final long serialVersionUID = 1997840387;

	/**
	 * Setter for <code>ratio_relations.dependent_id</code>.
	 */
	public void setDependentId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ratio_relations.dependent_id</code>.
	 */
	public java.lang.Long getDependentId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>ratio_relations.dependency_id</code>.
	 */
	public void setDependencyId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ratio_relations.dependency_id</code>.
	 */
	public java.lang.Long getDependencyId() {
		return (java.lang.Long) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.Long, java.lang.Long> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.Long> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.Long> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return genericdwh.db.model.tables.RatioRelations.RATIO_RELATIONS.DEPENDENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return genericdwh.db.model.tables.RatioRelations.RATIO_RELATIONS.DEPENDENCY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getDependentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getDependencyId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RatioRelationsRecord value1(java.lang.Long value) {
		setDependentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RatioRelationsRecord value2(java.lang.Long value) {
		setDependencyId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RatioRelationsRecord values(java.lang.Long value1, java.lang.Long value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RatioRelationsRecord
	 */
	public RatioRelationsRecord() {
		super(genericdwh.db.model.tables.RatioRelations.RATIO_RELATIONS);
	}

	/**
	 * Create a detached, initialised RatioRelationsRecord
	 */
	public RatioRelationsRecord(java.lang.Long dependentId, java.lang.Long dependencyId) {
		super(genericdwh.db.model.tables.RatioRelations.RATIO_RELATIONS);

		setValue(0, dependentId);
		setValue(1, dependencyId);
	}
}
