/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReferenceObjectsRecord extends org.jooq.impl.UpdatableRecordImpl<genericdwh.db.model.tables.records.ReferenceObjectsRecord> implements org.jooq.Record3<java.lang.Long, java.lang.Long, java.lang.String> {

	private static final long serialVersionUID = 193527865;

	/**
	 * Setter for <code>reference_objects.reference_object_id</code>.
	 */
	public void setReferenceObjectId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>reference_objects.reference_object_id</code>.
	 */
	public java.lang.Long getReferenceObjectId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>reference_objects.dimension_id</code>.
	 */
	public void setDimensionId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>reference_objects.dimension_id</code>.
	 */
	public java.lang.Long getDimensionId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>reference_objects.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>reference_objects.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Long, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Long, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return genericdwh.db.model.tables.ReferenceObjects.REFERENCE_OBJECTS.REFERENCE_OBJECT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return genericdwh.db.model.tables.ReferenceObjects.REFERENCE_OBJECTS.DIMENSION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return genericdwh.db.model.tables.ReferenceObjects.REFERENCE_OBJECTS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getReferenceObjectId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getDimensionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReferenceObjectsRecord value1(java.lang.Long value) {
		setReferenceObjectId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReferenceObjectsRecord value2(java.lang.Long value) {
		setDimensionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReferenceObjectsRecord value3(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReferenceObjectsRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ReferenceObjectsRecord
	 */
	public ReferenceObjectsRecord() {
		super(genericdwh.db.model.tables.ReferenceObjects.REFERENCE_OBJECTS);
	}

	/**
	 * Create a detached, initialised ReferenceObjectsRecord
	 */
	public ReferenceObjectsRecord(java.lang.Long referenceObjectId, java.lang.Long dimensionId, java.lang.String name) {
		super(genericdwh.db.model.tables.ReferenceObjects.REFERENCE_OBJECTS);

		setValue(0, referenceObjectId);
		setValue(1, dimensionId);
		setValue(2, name);
	}
}
