/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReferenceObjectRecord extends org.jooq.impl.UpdatableRecordImpl<genericdwh.db.model.tables.records.ReferenceObjectRecord> implements org.jooq.Record3<java.lang.Long, java.lang.Long, java.lang.String> {

	private static final long serialVersionUID = -1552591961;

	/**
	 * Setter for <code>genericdwh.reference_object.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>genericdwh.reference_object.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>genericdwh.reference_object.dimension_id</code>.
	 */
	public void setDimensionId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>genericdwh.reference_object.dimension_id</code>.
	 */
	public java.lang.Long getDimensionId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>genericdwh.reference_object.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>genericdwh.reference_object.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Long, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Long, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	public org.jooq.Field<java.lang.Long> field1() {
		return genericdwh.db.model.tables.ReferenceObject.REFERENCE_OBJECT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	public org.jooq.Field<java.lang.Long> field2() {
		return genericdwh.db.model.tables.ReferenceObject.REFERENCE_OBJECT.DIMENSION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	public org.jooq.Field<java.lang.String> field3() {
		return genericdwh.db.model.tables.ReferenceObject.REFERENCE_OBJECT.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	public java.lang.Long value2() {
		return getDimensionId();
	}

	/**
	 * {@inheritDoc}
	 */
	public java.lang.String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	public ReferenceObjectRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	public ReferenceObjectRecord value2(java.lang.Long value) {
		setDimensionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	public ReferenceObjectRecord value3(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	public ReferenceObjectRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ReferenceObjectRecord
	 */
	public ReferenceObjectRecord() {
		super(genericdwh.db.model.tables.ReferenceObject.REFERENCE_OBJECT);
	}

	/**
	 * Create a detached, initialised ReferenceObjectRecord
	 */
	public ReferenceObjectRecord(java.lang.Long id, java.lang.Long dimensionId, java.lang.String name) {
		super(genericdwh.db.model.tables.ReferenceObject.REFERENCE_OBJECT);

		setValue(0, id);
		setValue(1, dimensionId);
		setValue(2, name);
	}
}
