/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>genericdwh</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<genericdwh.db.model.tables.records.DimensionRecord, java.lang.Long> IDENTITY_DIMENSION = Identities0.IDENTITY_DIMENSION;
	public static final org.jooq.Identity<genericdwh.db.model.tables.records.DimensionCategoryRecord, java.lang.Long> IDENTITY_DIMENSION_CATEGORY = Identities0.IDENTITY_DIMENSION_CATEGORY;
	public static final org.jooq.Identity<genericdwh.db.model.tables.records.ReferenceObjectRecord, java.lang.Long> IDENTITY_REFERENCE_OBJECT = Identities0.IDENTITY_REFERENCE_OBJECT;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionRecord> KEY_DIMENSION_PRIMARY = UniqueKeys0.KEY_DIMENSION_PRIMARY;
	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionRecord> KEY_DIMENSION_ID = UniqueKeys0.KEY_DIMENSION_ID;
	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionCategoryRecord> KEY_DIMENSION_CATEGORY_PRIMARY = UniqueKeys0.KEY_DIMENSION_CATEGORY_PRIMARY;
	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionCategoryRecord> KEY_DIMENSION_CATEGORY_ID = UniqueKeys0.KEY_DIMENSION_CATEGORY_ID;
	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionCombinationRecord> KEY_DIMENSION_COMBINATION_PRIMARY = UniqueKeys0.KEY_DIMENSION_COMBINATION_PRIMARY;
	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionHierarchyRecord> KEY_DIMENSION_HIERARCHY_PRIMARY = UniqueKeys0.KEY_DIMENSION_HIERARCHY_PRIMARY;
	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectRecord> KEY_REFERENCE_OBJECT_PRIMARY = UniqueKeys0.KEY_REFERENCE_OBJECT_PRIMARY;
	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectRecord> KEY_REFERENCE_OBJECT_ID = UniqueKeys0.KEY_REFERENCE_OBJECT_ID;
	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectCombinationRecord> KEY_REFERENCE_OBJECT_COMBINATION_PRIMARY = UniqueKeys0.KEY_REFERENCE_OBJECT_COMBINATION_PRIMARY;
	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectHierarchyRecord> KEY_REFERENCE_OBJECT_HIERARCHY_PRIMARY = UniqueKeys0.KEY_REFERENCE_OBJECT_HIERARCHY_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionRecord, genericdwh.db.model.tables.records.DimensionCategoryRecord> DIMENSION_IBFK_1 = ForeignKeys0.DIMENSION_IBFK_1;
	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionCombinationRecord, genericdwh.db.model.tables.records.DimensionRecord> DIMENSION_COMBINATION_IBFK_1 = ForeignKeys0.DIMENSION_COMBINATION_IBFK_1;
	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionCombinationRecord, genericdwh.db.model.tables.records.DimensionRecord> DIMENSION_COMBINATION_IBFK_2 = ForeignKeys0.DIMENSION_COMBINATION_IBFK_2;
	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionHierarchyRecord, genericdwh.db.model.tables.records.DimensionRecord> DIMENSION_HIERARCHY_IBFK_1 = ForeignKeys0.DIMENSION_HIERARCHY_IBFK_1;
	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionHierarchyRecord, genericdwh.db.model.tables.records.DimensionRecord> DIMENSION_HIERARCHY_IBFK_2 = ForeignKeys0.DIMENSION_HIERARCHY_IBFK_2;
	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectRecord, genericdwh.db.model.tables.records.DimensionRecord> REFERENCE_OBJECT_IBFK_1 = ForeignKeys0.REFERENCE_OBJECT_IBFK_1;
	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectCombinationRecord, genericdwh.db.model.tables.records.ReferenceObjectRecord> REFERENCE_OBJECT_COMBINATION_IBFK_1 = ForeignKeys0.REFERENCE_OBJECT_COMBINATION_IBFK_1;
	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectCombinationRecord, genericdwh.db.model.tables.records.ReferenceObjectRecord> REFERENCE_OBJECT_COMBINATION_IBFK_2 = ForeignKeys0.REFERENCE_OBJECT_COMBINATION_IBFK_2;
	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectHierarchyRecord, genericdwh.db.model.tables.records.ReferenceObjectRecord> REFERENCE_OBJECT_HIERARCHY_IBFK_1 = ForeignKeys0.REFERENCE_OBJECT_HIERARCHY_IBFK_1;
	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectHierarchyRecord, genericdwh.db.model.tables.records.ReferenceObjectRecord> REFERENCE_OBJECT_HIERARCHY_IBFK_2 = ForeignKeys0.REFERENCE_OBJECT_HIERARCHY_IBFK_2;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<genericdwh.db.model.tables.records.DimensionRecord, java.lang.Long> IDENTITY_DIMENSION = createIdentity(genericdwh.db.model.tables.Dimension.DIMENSION, genericdwh.db.model.tables.Dimension.DIMENSION.ID);
		public static org.jooq.Identity<genericdwh.db.model.tables.records.DimensionCategoryRecord, java.lang.Long> IDENTITY_DIMENSION_CATEGORY = createIdentity(genericdwh.db.model.tables.DimensionCategory.DIMENSION_CATEGORY, genericdwh.db.model.tables.DimensionCategory.DIMENSION_CATEGORY.ID);
		public static org.jooq.Identity<genericdwh.db.model.tables.records.ReferenceObjectRecord, java.lang.Long> IDENTITY_REFERENCE_OBJECT = createIdentity(genericdwh.db.model.tables.ReferenceObject.REFERENCE_OBJECT, genericdwh.db.model.tables.ReferenceObject.REFERENCE_OBJECT.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionRecord> KEY_DIMENSION_PRIMARY = createUniqueKey(genericdwh.db.model.tables.Dimension.DIMENSION, genericdwh.db.model.tables.Dimension.DIMENSION.ID);
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionRecord> KEY_DIMENSION_ID = createUniqueKey(genericdwh.db.model.tables.Dimension.DIMENSION, genericdwh.db.model.tables.Dimension.DIMENSION.ID);
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionCategoryRecord> KEY_DIMENSION_CATEGORY_PRIMARY = createUniqueKey(genericdwh.db.model.tables.DimensionCategory.DIMENSION_CATEGORY, genericdwh.db.model.tables.DimensionCategory.DIMENSION_CATEGORY.ID);
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionCategoryRecord> KEY_DIMENSION_CATEGORY_ID = createUniqueKey(genericdwh.db.model.tables.DimensionCategory.DIMENSION_CATEGORY, genericdwh.db.model.tables.DimensionCategory.DIMENSION_CATEGORY.ID);
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionCombinationRecord> KEY_DIMENSION_COMBINATION_PRIMARY = createUniqueKey(genericdwh.db.model.tables.DimensionCombination.DIMENSION_COMBINATION, genericdwh.db.model.tables.DimensionCombination.DIMENSION_COMBINATION.AGGREGATE_ID, genericdwh.db.model.tables.DimensionCombination.DIMENSION_COMBINATION.COMPONENT_ID);
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionHierarchyRecord> KEY_DIMENSION_HIERARCHY_PRIMARY = createUniqueKey(genericdwh.db.model.tables.DimensionHierarchy.DIMENSION_HIERARCHY, genericdwh.db.model.tables.DimensionHierarchy.DIMENSION_HIERARCHY.PARENT_ID, genericdwh.db.model.tables.DimensionHierarchy.DIMENSION_HIERARCHY.CHILD_ID);
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectRecord> KEY_REFERENCE_OBJECT_PRIMARY = createUniqueKey(genericdwh.db.model.tables.ReferenceObject.REFERENCE_OBJECT, genericdwh.db.model.tables.ReferenceObject.REFERENCE_OBJECT.ID);
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectRecord> KEY_REFERENCE_OBJECT_ID = createUniqueKey(genericdwh.db.model.tables.ReferenceObject.REFERENCE_OBJECT, genericdwh.db.model.tables.ReferenceObject.REFERENCE_OBJECT.ID);
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectCombinationRecord> KEY_REFERENCE_OBJECT_COMBINATION_PRIMARY = createUniqueKey(genericdwh.db.model.tables.ReferenceObjectCombination.REFERENCE_OBJECT_COMBINATION, genericdwh.db.model.tables.ReferenceObjectCombination.REFERENCE_OBJECT_COMBINATION.AGGREGATE_ID, genericdwh.db.model.tables.ReferenceObjectCombination.REFERENCE_OBJECT_COMBINATION.COMPONENT_ID);
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectHierarchyRecord> KEY_REFERENCE_OBJECT_HIERARCHY_PRIMARY = createUniqueKey(genericdwh.db.model.tables.ReferenceObjectHierarchy.REFERENCE_OBJECT_HIERARCHY, genericdwh.db.model.tables.ReferenceObjectHierarchy.REFERENCE_OBJECT_HIERARCHY.PARENT_ID, genericdwh.db.model.tables.ReferenceObjectHierarchy.REFERENCE_OBJECT_HIERARCHY.CHILD_ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionRecord, genericdwh.db.model.tables.records.DimensionCategoryRecord> DIMENSION_IBFK_1 = createForeignKey(genericdwh.db.model.Keys.KEY_DIMENSION_CATEGORY_PRIMARY, genericdwh.db.model.tables.Dimension.DIMENSION, genericdwh.db.model.tables.Dimension.DIMENSION.CATEGORY_ID);
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionCombinationRecord, genericdwh.db.model.tables.records.DimensionRecord> DIMENSION_COMBINATION_IBFK_1 = createForeignKey(genericdwh.db.model.Keys.KEY_DIMENSION_PRIMARY, genericdwh.db.model.tables.DimensionCombination.DIMENSION_COMBINATION, genericdwh.db.model.tables.DimensionCombination.DIMENSION_COMBINATION.AGGREGATE_ID);
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionCombinationRecord, genericdwh.db.model.tables.records.DimensionRecord> DIMENSION_COMBINATION_IBFK_2 = createForeignKey(genericdwh.db.model.Keys.KEY_DIMENSION_PRIMARY, genericdwh.db.model.tables.DimensionCombination.DIMENSION_COMBINATION, genericdwh.db.model.tables.DimensionCombination.DIMENSION_COMBINATION.COMPONENT_ID);
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionHierarchyRecord, genericdwh.db.model.tables.records.DimensionRecord> DIMENSION_HIERARCHY_IBFK_1 = createForeignKey(genericdwh.db.model.Keys.KEY_DIMENSION_PRIMARY, genericdwh.db.model.tables.DimensionHierarchy.DIMENSION_HIERARCHY, genericdwh.db.model.tables.DimensionHierarchy.DIMENSION_HIERARCHY.PARENT_ID);
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionHierarchyRecord, genericdwh.db.model.tables.records.DimensionRecord> DIMENSION_HIERARCHY_IBFK_2 = createForeignKey(genericdwh.db.model.Keys.KEY_DIMENSION_PRIMARY, genericdwh.db.model.tables.DimensionHierarchy.DIMENSION_HIERARCHY, genericdwh.db.model.tables.DimensionHierarchy.DIMENSION_HIERARCHY.CHILD_ID);
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectRecord, genericdwh.db.model.tables.records.DimensionRecord> REFERENCE_OBJECT_IBFK_1 = createForeignKey(genericdwh.db.model.Keys.KEY_DIMENSION_PRIMARY, genericdwh.db.model.tables.ReferenceObject.REFERENCE_OBJECT, genericdwh.db.model.tables.ReferenceObject.REFERENCE_OBJECT.DIMENSION_ID);
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectCombinationRecord, genericdwh.db.model.tables.records.ReferenceObjectRecord> REFERENCE_OBJECT_COMBINATION_IBFK_1 = createForeignKey(genericdwh.db.model.Keys.KEY_REFERENCE_OBJECT_PRIMARY, genericdwh.db.model.tables.ReferenceObjectCombination.REFERENCE_OBJECT_COMBINATION, genericdwh.db.model.tables.ReferenceObjectCombination.REFERENCE_OBJECT_COMBINATION.AGGREGATE_ID);
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectCombinationRecord, genericdwh.db.model.tables.records.ReferenceObjectRecord> REFERENCE_OBJECT_COMBINATION_IBFK_2 = createForeignKey(genericdwh.db.model.Keys.KEY_REFERENCE_OBJECT_PRIMARY, genericdwh.db.model.tables.ReferenceObjectCombination.REFERENCE_OBJECT_COMBINATION, genericdwh.db.model.tables.ReferenceObjectCombination.REFERENCE_OBJECT_COMBINATION.COMPONENT_ID);
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectHierarchyRecord, genericdwh.db.model.tables.records.ReferenceObjectRecord> REFERENCE_OBJECT_HIERARCHY_IBFK_1 = createForeignKey(genericdwh.db.model.Keys.KEY_REFERENCE_OBJECT_PRIMARY, genericdwh.db.model.tables.ReferenceObjectHierarchy.REFERENCE_OBJECT_HIERARCHY, genericdwh.db.model.tables.ReferenceObjectHierarchy.REFERENCE_OBJECT_HIERARCHY.PARENT_ID);
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectHierarchyRecord, genericdwh.db.model.tables.records.ReferenceObjectRecord> REFERENCE_OBJECT_HIERARCHY_IBFK_2 = createForeignKey(genericdwh.db.model.Keys.KEY_REFERENCE_OBJECT_PRIMARY, genericdwh.db.model.tables.ReferenceObjectHierarchy.REFERENCE_OBJECT_HIERARCHY, genericdwh.db.model.tables.ReferenceObjectHierarchy.REFERENCE_OBJECT_HIERARCHY.CHILD_ID);
	}
}
