/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code></code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<genericdwh.db.model.tables.records.DimensionsRecord, java.lang.Long> IDENTITY_DIMENSIONS = Identities0.IDENTITY_DIMENSIONS;
	public static final org.jooq.Identity<genericdwh.db.model.tables.records.DimensionCategoriesRecord, java.lang.Long> IDENTITY_DIMENSION_CATEGORIES = Identities0.IDENTITY_DIMENSION_CATEGORIES;
	public static final org.jooq.Identity<genericdwh.db.model.tables.records.RatiosRecord, java.lang.Long> IDENTITY_RATIOS = Identities0.IDENTITY_RATIOS;
	public static final org.jooq.Identity<genericdwh.db.model.tables.records.RatioCategoriesRecord, java.lang.Long> IDENTITY_RATIO_CATEGORIES = Identities0.IDENTITY_RATIO_CATEGORIES;
	public static final org.jooq.Identity<genericdwh.db.model.tables.records.ReferenceObjectsRecord, java.lang.Long> IDENTITY_REFERENCE_OBJECTS = Identities0.IDENTITY_REFERENCE_OBJECTS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionsRecord> KEY_DIMENSIONS_PRIMARY = UniqueKeys0.KEY_DIMENSIONS_PRIMARY;
	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionsRecord> KEY_DIMENSIONS_DIMENSION_ID = UniqueKeys0.KEY_DIMENSIONS_DIMENSION_ID;
	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionCategoriesRecord> KEY_DIMENSION_CATEGORIES_PRIMARY = UniqueKeys0.KEY_DIMENSION_CATEGORIES_PRIMARY;
	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionCategoriesRecord> KEY_DIMENSION_CATEGORIES_CATEGORY_ID = UniqueKeys0.KEY_DIMENSION_CATEGORIES_CATEGORY_ID;
	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionCombinationsRecord> KEY_DIMENSION_COMBINATIONS_PRIMARY = UniqueKeys0.KEY_DIMENSION_COMBINATIONS_PRIMARY;
	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionHierarchiesRecord> KEY_DIMENSION_HIERARCHIES_PRIMARY = UniqueKeys0.KEY_DIMENSION_HIERARCHIES_PRIMARY;
	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.FactsRecord> KEY_FACTS_PRIMARY = UniqueKeys0.KEY_FACTS_PRIMARY;
	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.RatiosRecord> KEY_RATIOS_PRIMARY = UniqueKeys0.KEY_RATIOS_PRIMARY;
	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.RatioCategoriesRecord> KEY_RATIO_CATEGORIES_PRIMARY = UniqueKeys0.KEY_RATIO_CATEGORIES_PRIMARY;
	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.RatioCategoriesRecord> KEY_RATIO_CATEGORIES_CATEGORY_ID = UniqueKeys0.KEY_RATIO_CATEGORIES_CATEGORY_ID;
	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.RatioRelationsRecord> KEY_RATIO_RELATIONS_PRIMARY = UniqueKeys0.KEY_RATIO_RELATIONS_PRIMARY;
	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectsRecord> KEY_REFERENCE_OBJECTS_PRIMARY = UniqueKeys0.KEY_REFERENCE_OBJECTS_PRIMARY;
	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectsRecord> KEY_REFERENCE_OBJECTS_REFERENCE_OBJECT_ID = UniqueKeys0.KEY_REFERENCE_OBJECTS_REFERENCE_OBJECT_ID;
	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectCombinationsRecord> KEY_REFERENCE_OBJECT_COMBINATIONS_PRIMARY = UniqueKeys0.KEY_REFERENCE_OBJECT_COMBINATIONS_PRIMARY;
	public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectHierarchiesRecord> KEY_REFERENCE_OBJECT_HIERARCHIES_PRIMARY = UniqueKeys0.KEY_REFERENCE_OBJECT_HIERARCHIES_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionsRecord, genericdwh.db.model.tables.records.DimensionCategoriesRecord> DIMENSIONS_IBFK_1 = ForeignKeys0.DIMENSIONS_IBFK_1;
	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionCombinationsRecord, genericdwh.db.model.tables.records.DimensionsRecord> DIMENSION_COMBINATIONS_IBFK_1 = ForeignKeys0.DIMENSION_COMBINATIONS_IBFK_1;
	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionCombinationsRecord, genericdwh.db.model.tables.records.DimensionsRecord> DIMENSION_COMBINATIONS_IBFK_2 = ForeignKeys0.DIMENSION_COMBINATIONS_IBFK_2;
	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionHierarchiesRecord, genericdwh.db.model.tables.records.DimensionsRecord> DIMENSION_HIERARCHIES_IBFK_1 = ForeignKeys0.DIMENSION_HIERARCHIES_IBFK_1;
	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionHierarchiesRecord, genericdwh.db.model.tables.records.DimensionsRecord> DIMENSION_HIERARCHIES_IBFK_2 = ForeignKeys0.DIMENSION_HIERARCHIES_IBFK_2;
	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.FactsRecord, genericdwh.db.model.tables.records.RatiosRecord> FACTS_IBFK_1 = ForeignKeys0.FACTS_IBFK_1;
	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.FactsRecord, genericdwh.db.model.tables.records.ReferenceObjectsRecord> FACTS_IBFK_2 = ForeignKeys0.FACTS_IBFK_2;
	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.RatiosRecord, genericdwh.db.model.tables.records.RatioCategoriesRecord> RATIOS_IBFK_1 = ForeignKeys0.RATIOS_IBFK_1;
	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.RatioRelationsRecord, genericdwh.db.model.tables.records.RatiosRecord> RATIO_RELATIONS_IBFK_1 = ForeignKeys0.RATIO_RELATIONS_IBFK_1;
	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.RatioRelationsRecord, genericdwh.db.model.tables.records.RatiosRecord> RATIO_RELATIONS_IBFK_2 = ForeignKeys0.RATIO_RELATIONS_IBFK_2;
	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectsRecord, genericdwh.db.model.tables.records.DimensionsRecord> REFERENCE_OBJECTS_IBFK_1 = ForeignKeys0.REFERENCE_OBJECTS_IBFK_1;
	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectCombinationsRecord, genericdwh.db.model.tables.records.ReferenceObjectsRecord> REFERENCE_OBJECT_COMBINATIONS_IBFK_1 = ForeignKeys0.REFERENCE_OBJECT_COMBINATIONS_IBFK_1;
	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectCombinationsRecord, genericdwh.db.model.tables.records.ReferenceObjectsRecord> REFERENCE_OBJECT_COMBINATIONS_IBFK_2 = ForeignKeys0.REFERENCE_OBJECT_COMBINATIONS_IBFK_2;
	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectHierarchiesRecord, genericdwh.db.model.tables.records.ReferenceObjectsRecord> REFERENCE_OBJECT_HIERARCHIES_IBFK_1 = ForeignKeys0.REFERENCE_OBJECT_HIERARCHIES_IBFK_1;
	public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectHierarchiesRecord, genericdwh.db.model.tables.records.ReferenceObjectsRecord> REFERENCE_OBJECT_HIERARCHIES_IBFK_2 = ForeignKeys0.REFERENCE_OBJECT_HIERARCHIES_IBFK_2;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<genericdwh.db.model.tables.records.DimensionsRecord, java.lang.Long> IDENTITY_DIMENSIONS = createIdentity(genericdwh.db.model.tables.Dimensions.DIMENSIONS, genericdwh.db.model.tables.Dimensions.DIMENSIONS.DIMENSION_ID);
		public static org.jooq.Identity<genericdwh.db.model.tables.records.DimensionCategoriesRecord, java.lang.Long> IDENTITY_DIMENSION_CATEGORIES = createIdentity(genericdwh.db.model.tables.DimensionCategories.DIMENSION_CATEGORIES, genericdwh.db.model.tables.DimensionCategories.DIMENSION_CATEGORIES.CATEGORY_ID);
		public static org.jooq.Identity<genericdwh.db.model.tables.records.RatiosRecord, java.lang.Long> IDENTITY_RATIOS = createIdentity(genericdwh.db.model.tables.Ratios.RATIOS, genericdwh.db.model.tables.Ratios.RATIOS.RATIO_ID);
		public static org.jooq.Identity<genericdwh.db.model.tables.records.RatioCategoriesRecord, java.lang.Long> IDENTITY_RATIO_CATEGORIES = createIdentity(genericdwh.db.model.tables.RatioCategories.RATIO_CATEGORIES, genericdwh.db.model.tables.RatioCategories.RATIO_CATEGORIES.CATEGORY_ID);
		public static org.jooq.Identity<genericdwh.db.model.tables.records.ReferenceObjectsRecord, java.lang.Long> IDENTITY_REFERENCE_OBJECTS = createIdentity(genericdwh.db.model.tables.ReferenceObjects.REFERENCE_OBJECTS, genericdwh.db.model.tables.ReferenceObjects.REFERENCE_OBJECTS.REFERENCE_OBJECT_ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionsRecord> KEY_DIMENSIONS_PRIMARY = createUniqueKey(genericdwh.db.model.tables.Dimensions.DIMENSIONS, genericdwh.db.model.tables.Dimensions.DIMENSIONS.DIMENSION_ID);
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionsRecord> KEY_DIMENSIONS_DIMENSION_ID = createUniqueKey(genericdwh.db.model.tables.Dimensions.DIMENSIONS, genericdwh.db.model.tables.Dimensions.DIMENSIONS.DIMENSION_ID);
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionCategoriesRecord> KEY_DIMENSION_CATEGORIES_PRIMARY = createUniqueKey(genericdwh.db.model.tables.DimensionCategories.DIMENSION_CATEGORIES, genericdwh.db.model.tables.DimensionCategories.DIMENSION_CATEGORIES.CATEGORY_ID);
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionCategoriesRecord> KEY_DIMENSION_CATEGORIES_CATEGORY_ID = createUniqueKey(genericdwh.db.model.tables.DimensionCategories.DIMENSION_CATEGORIES, genericdwh.db.model.tables.DimensionCategories.DIMENSION_CATEGORIES.CATEGORY_ID);
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionCombinationsRecord> KEY_DIMENSION_COMBINATIONS_PRIMARY = createUniqueKey(genericdwh.db.model.tables.DimensionCombinations.DIMENSION_COMBINATIONS, genericdwh.db.model.tables.DimensionCombinations.DIMENSION_COMBINATIONS.AGGREGATE_ID, genericdwh.db.model.tables.DimensionCombinations.DIMENSION_COMBINATIONS.COMPONENT_ID);
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.DimensionHierarchiesRecord> KEY_DIMENSION_HIERARCHIES_PRIMARY = createUniqueKey(genericdwh.db.model.tables.DimensionHierarchies.DIMENSION_HIERARCHIES, genericdwh.db.model.tables.DimensionHierarchies.DIMENSION_HIERARCHIES.PARENT_ID, genericdwh.db.model.tables.DimensionHierarchies.DIMENSION_HIERARCHIES.CHILD_ID);
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.FactsRecord> KEY_FACTS_PRIMARY = createUniqueKey(genericdwh.db.model.tables.Facts.FACTS, genericdwh.db.model.tables.Facts.FACTS.RATIO_ID, genericdwh.db.model.tables.Facts.FACTS.REFERENCE_OBJECT_ID);
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.RatiosRecord> KEY_RATIOS_PRIMARY = createUniqueKey(genericdwh.db.model.tables.Ratios.RATIOS, genericdwh.db.model.tables.Ratios.RATIOS.RATIO_ID);
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.RatioCategoriesRecord> KEY_RATIO_CATEGORIES_PRIMARY = createUniqueKey(genericdwh.db.model.tables.RatioCategories.RATIO_CATEGORIES, genericdwh.db.model.tables.RatioCategories.RATIO_CATEGORIES.CATEGORY_ID);
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.RatioCategoriesRecord> KEY_RATIO_CATEGORIES_CATEGORY_ID = createUniqueKey(genericdwh.db.model.tables.RatioCategories.RATIO_CATEGORIES, genericdwh.db.model.tables.RatioCategories.RATIO_CATEGORIES.CATEGORY_ID);
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.RatioRelationsRecord> KEY_RATIO_RELATIONS_PRIMARY = createUniqueKey(genericdwh.db.model.tables.RatioRelations.RATIO_RELATIONS, genericdwh.db.model.tables.RatioRelations.RATIO_RELATIONS.DEPENDENT_ID, genericdwh.db.model.tables.RatioRelations.RATIO_RELATIONS.DEPENDENCY_ID);
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectsRecord> KEY_REFERENCE_OBJECTS_PRIMARY = createUniqueKey(genericdwh.db.model.tables.ReferenceObjects.REFERENCE_OBJECTS, genericdwh.db.model.tables.ReferenceObjects.REFERENCE_OBJECTS.REFERENCE_OBJECT_ID);
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectsRecord> KEY_REFERENCE_OBJECTS_REFERENCE_OBJECT_ID = createUniqueKey(genericdwh.db.model.tables.ReferenceObjects.REFERENCE_OBJECTS, genericdwh.db.model.tables.ReferenceObjects.REFERENCE_OBJECTS.REFERENCE_OBJECT_ID);
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectCombinationsRecord> KEY_REFERENCE_OBJECT_COMBINATIONS_PRIMARY = createUniqueKey(genericdwh.db.model.tables.ReferenceObjectCombinations.REFERENCE_OBJECT_COMBINATIONS, genericdwh.db.model.tables.ReferenceObjectCombinations.REFERENCE_OBJECT_COMBINATIONS.AGGREGATE_ID, genericdwh.db.model.tables.ReferenceObjectCombinations.REFERENCE_OBJECT_COMBINATIONS.COMPONENT_ID);
		public static final org.jooq.UniqueKey<genericdwh.db.model.tables.records.ReferenceObjectHierarchiesRecord> KEY_REFERENCE_OBJECT_HIERARCHIES_PRIMARY = createUniqueKey(genericdwh.db.model.tables.ReferenceObjectHierarchies.REFERENCE_OBJECT_HIERARCHIES, genericdwh.db.model.tables.ReferenceObjectHierarchies.REFERENCE_OBJECT_HIERARCHIES.PARENT_ID, genericdwh.db.model.tables.ReferenceObjectHierarchies.REFERENCE_OBJECT_HIERARCHIES.CHILD_ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionsRecord, genericdwh.db.model.tables.records.DimensionCategoriesRecord> DIMENSIONS_IBFK_1 = createForeignKey(genericdwh.db.model.Keys.KEY_DIMENSION_CATEGORIES_PRIMARY, genericdwh.db.model.tables.Dimensions.DIMENSIONS, genericdwh.db.model.tables.Dimensions.DIMENSIONS.CATEGORY_ID);
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionCombinationsRecord, genericdwh.db.model.tables.records.DimensionsRecord> DIMENSION_COMBINATIONS_IBFK_1 = createForeignKey(genericdwh.db.model.Keys.KEY_DIMENSIONS_PRIMARY, genericdwh.db.model.tables.DimensionCombinations.DIMENSION_COMBINATIONS, genericdwh.db.model.tables.DimensionCombinations.DIMENSION_COMBINATIONS.AGGREGATE_ID);
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionCombinationsRecord, genericdwh.db.model.tables.records.DimensionsRecord> DIMENSION_COMBINATIONS_IBFK_2 = createForeignKey(genericdwh.db.model.Keys.KEY_DIMENSIONS_PRIMARY, genericdwh.db.model.tables.DimensionCombinations.DIMENSION_COMBINATIONS, genericdwh.db.model.tables.DimensionCombinations.DIMENSION_COMBINATIONS.COMPONENT_ID);
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionHierarchiesRecord, genericdwh.db.model.tables.records.DimensionsRecord> DIMENSION_HIERARCHIES_IBFK_1 = createForeignKey(genericdwh.db.model.Keys.KEY_DIMENSIONS_PRIMARY, genericdwh.db.model.tables.DimensionHierarchies.DIMENSION_HIERARCHIES, genericdwh.db.model.tables.DimensionHierarchies.DIMENSION_HIERARCHIES.PARENT_ID);
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.DimensionHierarchiesRecord, genericdwh.db.model.tables.records.DimensionsRecord> DIMENSION_HIERARCHIES_IBFK_2 = createForeignKey(genericdwh.db.model.Keys.KEY_DIMENSIONS_PRIMARY, genericdwh.db.model.tables.DimensionHierarchies.DIMENSION_HIERARCHIES, genericdwh.db.model.tables.DimensionHierarchies.DIMENSION_HIERARCHIES.CHILD_ID);
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.FactsRecord, genericdwh.db.model.tables.records.RatiosRecord> FACTS_IBFK_1 = createForeignKey(genericdwh.db.model.Keys.KEY_RATIOS_PRIMARY, genericdwh.db.model.tables.Facts.FACTS, genericdwh.db.model.tables.Facts.FACTS.RATIO_ID);
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.FactsRecord, genericdwh.db.model.tables.records.ReferenceObjectsRecord> FACTS_IBFK_2 = createForeignKey(genericdwh.db.model.Keys.KEY_REFERENCE_OBJECTS_PRIMARY, genericdwh.db.model.tables.Facts.FACTS, genericdwh.db.model.tables.Facts.FACTS.REFERENCE_OBJECT_ID);
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.RatiosRecord, genericdwh.db.model.tables.records.RatioCategoriesRecord> RATIOS_IBFK_1 = createForeignKey(genericdwh.db.model.Keys.KEY_RATIO_CATEGORIES_PRIMARY, genericdwh.db.model.tables.Ratios.RATIOS, genericdwh.db.model.tables.Ratios.RATIOS.CATEGORY_ID);
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.RatioRelationsRecord, genericdwh.db.model.tables.records.RatiosRecord> RATIO_RELATIONS_IBFK_1 = createForeignKey(genericdwh.db.model.Keys.KEY_RATIOS_PRIMARY, genericdwh.db.model.tables.RatioRelations.RATIO_RELATIONS, genericdwh.db.model.tables.RatioRelations.RATIO_RELATIONS.DEPENDENT_ID);
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.RatioRelationsRecord, genericdwh.db.model.tables.records.RatiosRecord> RATIO_RELATIONS_IBFK_2 = createForeignKey(genericdwh.db.model.Keys.KEY_RATIOS_PRIMARY, genericdwh.db.model.tables.RatioRelations.RATIO_RELATIONS, genericdwh.db.model.tables.RatioRelations.RATIO_RELATIONS.DEPENDENCY_ID);
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectsRecord, genericdwh.db.model.tables.records.DimensionsRecord> REFERENCE_OBJECTS_IBFK_1 = createForeignKey(genericdwh.db.model.Keys.KEY_DIMENSIONS_PRIMARY, genericdwh.db.model.tables.ReferenceObjects.REFERENCE_OBJECTS, genericdwh.db.model.tables.ReferenceObjects.REFERENCE_OBJECTS.DIMENSION_ID);
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectCombinationsRecord, genericdwh.db.model.tables.records.ReferenceObjectsRecord> REFERENCE_OBJECT_COMBINATIONS_IBFK_1 = createForeignKey(genericdwh.db.model.Keys.KEY_REFERENCE_OBJECTS_PRIMARY, genericdwh.db.model.tables.ReferenceObjectCombinations.REFERENCE_OBJECT_COMBINATIONS, genericdwh.db.model.tables.ReferenceObjectCombinations.REFERENCE_OBJECT_COMBINATIONS.AGGREGATE_ID);
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectCombinationsRecord, genericdwh.db.model.tables.records.ReferenceObjectsRecord> REFERENCE_OBJECT_COMBINATIONS_IBFK_2 = createForeignKey(genericdwh.db.model.Keys.KEY_REFERENCE_OBJECTS_PRIMARY, genericdwh.db.model.tables.ReferenceObjectCombinations.REFERENCE_OBJECT_COMBINATIONS, genericdwh.db.model.tables.ReferenceObjectCombinations.REFERENCE_OBJECT_COMBINATIONS.COMPONENT_ID);
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectHierarchiesRecord, genericdwh.db.model.tables.records.ReferenceObjectsRecord> REFERENCE_OBJECT_HIERARCHIES_IBFK_1 = createForeignKey(genericdwh.db.model.Keys.KEY_REFERENCE_OBJECTS_PRIMARY, genericdwh.db.model.tables.ReferenceObjectHierarchies.REFERENCE_OBJECT_HIERARCHIES, genericdwh.db.model.tables.ReferenceObjectHierarchies.REFERENCE_OBJECT_HIERARCHIES.PARENT_ID);
		public static final org.jooq.ForeignKey<genericdwh.db.model.tables.records.ReferenceObjectHierarchiesRecord, genericdwh.db.model.tables.records.ReferenceObjectsRecord> REFERENCE_OBJECT_HIERARCHIES_IBFK_2 = createForeignKey(genericdwh.db.model.Keys.KEY_REFERENCE_OBJECTS_PRIMARY, genericdwh.db.model.tables.ReferenceObjectHierarchies.REFERENCE_OBJECT_HIERARCHIES, genericdwh.db.model.tables.ReferenceObjectHierarchies.REFERENCE_OBJECT_HIERARCHIES.CHILD_ID);
	}
}
