/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in 
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table dimension
	 */
	public static final genericdwh.db.model.tables.Dimension DIMENSION = genericdwh.db.model.tables.Dimension.DIMENSION;

	/**
	 * The table dimension_category
	 */
	public static final genericdwh.db.model.tables.DimensionCategory DIMENSION_CATEGORY = genericdwh.db.model.tables.DimensionCategory.DIMENSION_CATEGORY;

	/**
	 * The table dimension_combination
	 */
	public static final genericdwh.db.model.tables.DimensionCombination DIMENSION_COMBINATION = genericdwh.db.model.tables.DimensionCombination.DIMENSION_COMBINATION;

	/**
	 * The table dimension_hierarchy
	 */
	public static final genericdwh.db.model.tables.DimensionHierarchy DIMENSION_HIERARCHY = genericdwh.db.model.tables.DimensionHierarchy.DIMENSION_HIERARCHY;

	/**
	 * The table ratio
	 */
	public static final genericdwh.db.model.tables.Ratio RATIO = genericdwh.db.model.tables.Ratio.RATIO;

	/**
	 * The table ratio_category
	 */
	public static final genericdwh.db.model.tables.RatioCategory RATIO_CATEGORY = genericdwh.db.model.tables.RatioCategory.RATIO_CATEGORY;

	/**
	 * The table reference_object
	 */
	public static final genericdwh.db.model.tables.ReferenceObject REFERENCE_OBJECT = genericdwh.db.model.tables.ReferenceObject.REFERENCE_OBJECT;

	/**
	 * The table reference_object_combination
	 */
	public static final genericdwh.db.model.tables.ReferenceObjectCombination REFERENCE_OBJECT_COMBINATION = genericdwh.db.model.tables.ReferenceObjectCombination.REFERENCE_OBJECT_COMBINATION;

	/**
	 * The table reference_object_hierarchy
	 */
	public static final genericdwh.db.model.tables.ReferenceObjectHierarchy REFERENCE_OBJECT_HIERARCHY = genericdwh.db.model.tables.ReferenceObjectHierarchy.REFERENCE_OBJECT_HIERARCHY;
}
