/**
 * This class is generated by jOOQ
 */
package genericdwh.db.model;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in 
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table dimensions
	 */
	public static final genericdwh.db.model.tables.Dimensions DIMENSIONS = genericdwh.db.model.tables.Dimensions.DIMENSIONS;

	/**
	 * The table dimension_categories
	 */
	public static final genericdwh.db.model.tables.DimensionCategories DIMENSION_CATEGORIES = genericdwh.db.model.tables.DimensionCategories.DIMENSION_CATEGORIES;

	/**
	 * The table dimension_combinations
	 */
	public static final genericdwh.db.model.tables.DimensionCombinations DIMENSION_COMBINATIONS = genericdwh.db.model.tables.DimensionCombinations.DIMENSION_COMBINATIONS;

	/**
	 * The table dimension_hierarchies
	 */
	public static final genericdwh.db.model.tables.DimensionHierarchies DIMENSION_HIERARCHIES = genericdwh.db.model.tables.DimensionHierarchies.DIMENSION_HIERARCHIES;

	/**
	 * The table ratios
	 */
	public static final genericdwh.db.model.tables.Ratios RATIOS = genericdwh.db.model.tables.Ratios.RATIOS;

	/**
	 * The table ratio_categories
	 */
	public static final genericdwh.db.model.tables.RatioCategories RATIO_CATEGORIES = genericdwh.db.model.tables.RatioCategories.RATIO_CATEGORIES;

	/**
	 * The table ratio_relations
	 */
	public static final genericdwh.db.model.tables.RatioRelations RATIO_RELATIONS = genericdwh.db.model.tables.RatioRelations.RATIO_RELATIONS;

	/**
	 * The table reference_objects
	 */
	public static final genericdwh.db.model.tables.ReferenceObjects REFERENCE_OBJECTS = genericdwh.db.model.tables.ReferenceObjects.REFERENCE_OBJECTS;

	/**
	 * The table reference_object_combinations
	 */
	public static final genericdwh.db.model.tables.ReferenceObjectCombinations REFERENCE_OBJECT_COMBINATIONS = genericdwh.db.model.tables.ReferenceObjectCombinations.REFERENCE_OBJECT_COMBINATIONS;

	/**
	 * The table reference_object_hierarchies
	 */
	public static final genericdwh.db.model.tables.ReferenceObjectHierarchies REFERENCE_OBJECT_HIERARCHIES = genericdwh.db.model.tables.ReferenceObjectHierarchies.REFERENCE_OBJECT_HIERARCHIES;
}
